services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - JwtSettings__ExpirationInHours=24
    env_file:
      - .env
    volumes:
      - .:/workspace
      - backend-nuget-cache:/root/.nuget/packages
    depends_on:
      postgres-dev:
        condition: service_healthy
    networks:
      - skillforge-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000/api
      - VITE_SIGNALR_URL=http://localhost:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - skillforge-network

  postgres-dev:
    image: postgres:15-alpine
    container_name: skillforge-postgres-dev
    profiles: ["postgres", "default"]
    environment:
      POSTGRES_DB: skillforge_dev
      POSTGRES_USER: skillforge_test
      POSTGRES_PASSWORD: test_password_123
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5432:5432"  # Standard PostgreSQL port
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U skillforge_test -d skillforge_dev"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - skillforge-network
    # Optimise for development - good performance, reliable
    command: >
      postgres
      -c max_connections=100
      -c shared_buffers=128MB
      -c effective_cache_size=256MB
      -c wal_buffers=8MB

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    profiles: ["sqlserver"]
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Express
      - MSSQL_MEMORY_LIMIT_MB=1024
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -C -Q 'SELECT 1' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 40s
    networks:
      - skillforge-network

volumes:
  postgres-dev-data:
  sqlserver-data:
  backend-nuget-cache:

networks:
  skillforge-network:
    driver: bridge