version: '3.8'

services:
  postgres-test:
    image: postgres:15-alpine
    container_name: skillforge-postgres-test
    environment:
      POSTGRES_DB: skillforge_test
      POSTGRES_USER: skillforge_test
      POSTGRES_PASSWORD: test_password_123
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"  # Different port to avoid conflicts with dev databases
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U skillforge_test -d skillforge_test"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - test-network
    # Optimise for testing - faster startup, less durability for speed
    command: >
      postgres
      -c fsync=off
      -c synchronous_commit=off
      -c full_page_writes=off
      -c max_wal_size=1GB
      -c min_wal_size=80MB
      -c checkpoint_completion_target=0.9
      -c wal_buffers=16MB
      -c shared_buffers=256MB

volumes:
  postgres-test-data:
    driver: local

networks:
  test-network:
    driver: bridge

# Usage:
# docker-compose -f docker-compose.test.yml up -d
# Run tests, then:
# docker-compose -f docker-compose.test.yml down