name: skillforge-devcontainer
version: '3.8'
services:
  backend:
    build:
      context: ..
      dockerfile: backend/Dockerfile.dev
    volumes:
      - ..:/workspace:cached
      - backend-nuget-cache:/root/.nuget/packages
    working_dir: /workspace/backend
    command: /bin/sh -c "while sleep 1000; do :; done"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=SkillForge;User=sa;Password=${SA_PASSWORD};TrustServerCertificate=true
      - JwtSettings__SecretKey=${JWT_SECRET_KEY}
      - JwtSettings__ExpirationInHours=24
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      - skillforge-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}
      - MSSQL_PID=Express
      - MSSQL_MEMORY_LIMIT_MB=1024
    volumes:
      - sqlserver-data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -C -Q 'SELECT 1' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 40s
    networks:
      - skillforge-network

volumes:
  backend-nuget-cache:
  sqlserver-data:

networks:
  skillforge-network:
    driver: bridge