name: Build and Push Container Images

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - 'frontend/**'
      - '.github/workflows/build-and-push.yml'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  FRONTEND_IMAGE_NAME: ${{ github.repository }}-frontend
  BACKEND_IMAGE_NAME: ${{ github.repository }}-backend

jobs:
  build-backend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      image-tags: ${{ steps.meta.outputs.tags }}
      image-digest: ${{ steps.meta.outputs.digest }}
      registry: ${{ env.REGISTRY }}
      image-name: ${{ env.BACKEND_IMAGE_NAME }}

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: skillforge_test
          POSTGRES_USER: skillforge_test
          POSTGRES_PASSWORD: test_password_123
          POSTGRES_HOST_AUTH_METHOD: md5
        ports:
          - 5433:5432
        options: >-
          --health-cmd "pg_isready -U skillforge_test -d skillforge_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore SkillForge.sln

    - name: Build backend project
      run: dotnet build SkillForge.sln --no-restore --configuration Release

    - name: Run tests
      run: dotnet test SkillForge.sln --no-build --configuration Release --verbosity normal

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Backend
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.BACKEND_IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Backend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile.azure
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64

  build-frontend:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Frontend
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.FRONTEND_IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Frontend Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        file: ./frontend/Dockerfile.azure
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64
        build-args: |
          VITE_API_URL=https://skillforge-backend-HASH.australiaeast.azurecontainerapps.io/api
          VITE_SIGNALR_URL=https://skillforge-backend-HASH.australiaeast.azurecontainerapps.io

  security-scan:
    runs-on: ubuntu-latest
    needs: [build-backend, build-frontend]
    permissions:
      contents: read
      security-events: write
      packages: read

    steps:
    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ needs.build-backend.outputs.registry }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Extract primary image tag
      id: extract-tag
      run: |
        # Get the first line/tag from the multi-line tags output
        FIRST_TAG=$(echo "${{ needs.build-backend.outputs.image-tags }}" | head -n1)
        echo "image-tag=$FIRST_TAG" >> $GITHUB_OUTPUT
        echo "Image reference to scan: $FIRST_TAG"
        echo "All available tags:"
        echo "${{ needs.build-backend.outputs.image-tags }}"
        echo "Registry: ${{ needs.build-backend.outputs.registry }}"

    - name: Run Trivy vulnerability scanner - Backend
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ steps.extract-tag.outputs.image-tag }}
        format: 'sarif'
        output: 'backend-trivy-results.sarif'

    - name: Check if SARIF file exists
      id: check-sarif
      run: |
        if [[ -f "backend-trivy-results.sarif" ]]; then
          echo "sarif-exists=true" >> $GITHUB_OUTPUT
          echo "SARIF file found, will upload to GitHub Security"
        else
          echo "sarif-exists=false" >> $GITHUB_OUTPUT
          echo "SARIF file not found, skipping upload"
        fi

    - name: Upload Trivy scan results to GitHub Security
      uses: github/codeql-action/upload-sarif@v3
      if: steps.check-sarif.outputs.sarif-exists == 'true'
      with:
        sarif_file: 'backend-trivy-results.sarif'