name: Test GitHub Secrets

on:
  workflow_dispatch: # Manual trigger only

jobs:
  test-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Verify GCP Project ID
      run: |
        if [[ -n "$GCP_PROJECT_ID" ]]; then
          echo "✅ GCP_PROJECT_ID is set"
          echo "Project ID length: ${#GCP_PROJECT_ID}"
        else
          echo "❌ GCP_PROJECT_ID is not set"
          exit 1
        fi
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
    
    - name: Verify GCP Service Account Key
      run: |
        if [[ -n "$GCP_SA_KEY" ]]; then
          echo "✅ GCP_SA_KEY is set"
          echo "Key length: ${#GCP_SA_KEY}"
          # Validate JSON format
          echo "$GCP_SA_KEY" | jq . > /dev/null
          echo "✅ GCP_SA_KEY is valid JSON"
        else
          echo "❌ GCP_SA_KEY is not set"
          exit 1
        fi
      env:
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
    
    - name: Verify Production JWT Secret
      run: |
        if [[ -n "$PRODUCTION_JWT_SECRET_KEY" ]]; then
          echo "✅ PRODUCTION_JWT_SECRET_KEY is set"
          echo "Key length: ${#PRODUCTION_JWT_SECRET_KEY}"
        else
          echo "❌ PRODUCTION_JWT_SECRET_KEY is not set"
          exit 1
        fi
      env:
        PRODUCTION_JWT_SECRET_KEY: ${{ secrets.PRODUCTION_JWT_SECRET_KEY }}
    
    - name: Test GCP Authentication
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    
    - name: Verify GCP Access
      run: |
        gcloud config list
        gcloud auth list
        echo "✅ GCP authentication successful"